"""specfuse-orchestrator CLI: `init` / `upgrade` dispatch (FEAT-2026-0002/T01, gate 1).

`init <dir>` scaffolds the user-owned state repo (FEAT-2026-0002/T02): the
`features/`, `events/`, `project/`, `inbox/`, `overrides/` dirs and a starter
`roadmap.md`, replicating the state-repo half of the retired fork-era setup script. Seed
content is embedded below as packaged data (compiled into this module, not
read from a path in the orchestrator source tree) so it ships with the wheel.

`init <dir>` additionally (FEAT-2026-0002/T03): wires `.claude/settings.json` +
`.claude/CLAUDE.md` (marketplace, plugin, and deny-specs-edit hook — merge-safe,
add-if-absent), and writes `project/NEXT_STEPS.md` — the remainder of the
`scripts/setup.sh` replacement. `gh repo create` and the interactive org/repo
prompts stay out of scope (operator-run or a later flag).

`init` is local-first (FEAT-2026-0001/T01): it does NOT run `git init` unless
`--git` is passed, and even then it skips `git init` when `<dir>` already sits
inside a git repo (walking up parent directories) so it never nests a repo
inside one that already exists.

`init --target <component|specs> <repo>` (and `init --all`, `init --help`)
forward to `specfuse.orchestrator.init.main`, the pre-existing
ownership-manifest-driven substrate installer — a distinct concern (installing
the orchestrator's substrate into *other* repos) predating this feature.

`upgrade <dir>` (FEAT-2026-0002/T04, gate 2) copies the frozen substrate tree
from the installed wheel (`paths.substrate()`) into the consumer's `shared/`
mount, overwriting managed files in place. The mount name is derived from
`_RULES_SENTINEL` so it can never drift out of step with the `.claude/CLAUDE.md`
`@shared/rules/...` wiring `_write_claude_md` writes in `init`. The consumer's
user-owned state dirs (`STATE_DIRS` + `roadmap.md`) are never touched — `upgrade`
writes only under the substrate mount.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

from specfuse.orchestrator import __version__, paths

STATE_DIRS = ("features", "events", "project", "inbox", "overrides")

# Stamp file written under the substrate mount recording the wheel version
# that last provisioned it; self_provision_if_stale() compares against this
# to skip re-copying the tree on every steady-state driver run.
_SUBSTRATE_VERSION_STAMP = ".substrate-version"

# --- .claude wiring constants (mirror this repo's own .claude/settings.json,
# which is itself the downstream-facing constant: specfuse/loop/scaffold.py's
# _write_settings_json uses the identical marketplace/plugin shape). ---
_MARKETPLACE_KEY = "specfuse"
_MARKETPLACE_VALUE: dict = {
    "source": {
        "source": "github",
        "repo": "specfuse/specfuse",
    },
}
_PLUGIN_KEY = "specfuse@specfuse"
_DENY_HOOK_ENTRY: dict = {
    "matcher": "Edit|Write|MultiEdit|NotebookEdit",
    "hooks": [
        {
            "type": "command",
            "command": 'python3 "$CLAUDE_PROJECT_DIR/scripts/hooks/deny-specs-edit.py"',
        }
    ],
}

_RULES_BLOCK = (
    "## Specfuse orchestrator binding rules (read before any session)\n"
    "@shared/rules/correlation-ids.md\n"
    "@shared/rules/escalation-protocol.md\n"
    "@shared/rules/never-touch.md\n"
    "@shared/rules/override-registry.md\n"
    "@shared/rules/role-switch-hygiene.md\n"
    "@shared/rules/security-boundaries.md\n"
    "@shared/rules/state-vocabulary.md\n"
    "@shared/rules/verify-before-report.md\n"
)
_RULES_SENTINEL = "@shared/rules/never-touch.md"

_NEXT_STEPS_TEMPLATE = """\
# Next steps — {project_name}

Generated by `specfuse-orchestrator init`.

This orchestration repo's state dirs (`features/`, `events/`, `project/`,
`inbox/`, `overrides/`, `roadmap.md`) are scaffolded and `.claude/` is wired
(marketplace, plugin, deny-specs-edit hook).

## What to do next

1. Open a Claude Code session at this repo.
2. Run `/onboard` — the onboarding agent inventories your repos and drafts a
   bootstrap checklist or integration plan.
3. Once onboarding says you're ready, draft your first feature and hand it to
   the loop per `docs/operator-runbook.md`.
"""

ROADMAP_SEED = """\
---
project: <orchestration repo / installation name>
---

# Initiative roadmap

The master index of this orchestration repo's **initiatives** — the cross-repo,
spec-driven units of product value the orchestrator coordinates. The
initiative-grain analog of the loop's per-repo `roadmap.md`, one level up the
hierarchy: `initiative -> feature -> gate -> work unit`.

**One fact, one home.** This roadmap owns *initiative definitions* and a
*pointer to live state*. The canonical state lives in each initiative's registry
frontmatter at `features/INIT-YYYY-NNNN.md` (`state:`, `feature_graph:`); the
registry owns the feature graph; each dispatched feature's **loop** owns that
feature's gates and work units. When this table and a registry disagree, the
**registry wins**.

The roadmap covers initiatives from `planning` onward. The pre-planning states
`drafting` and `validating` happen in the specs repo's ideation backlog; an
initiative graduates onto this roadmap when the specs agent hands it to the PM
at `planning`.

| Initiative ID  | Title    | State    | Registry | Repos |
|----------------|----------|----------|----------|-------|
| INIT-2026-0001 | <title>  | planning | `features/INIT-2026-0001.md` | <repos> |

State (canonical lifecycle): `planning` -> `plan_review` -> `generating` ->
`in_progress` -> (`blocked` <-> `in_progress`) -> `done` / `abandoned`.
Pre-roadmap (specs repo): `drafting` -> `validating` -> `planning`.
"""


def _scaffold_state_dirs(target_dir: Path) -> None:
    """Create the user-owned state dirs + a starter roadmap.md under `target_dir`.

    Idempotent: existing dirs and an existing roadmap.md (or any other
    pre-existing user content) are left untouched.
    """
    for name in STATE_DIRS:
        (target_dir / name).mkdir(parents=True, exist_ok=True)
    roadmap = target_dir / "roadmap.md"
    if not roadmap.exists():
        roadmap.write_text(ROADMAP_SEED)


def _inside_existing_repo(target_dir: Path) -> bool:
    """True if `target_dir` (or an ancestor of it) is already a git repo.

    Walks up from `target_dir`'s resolved path checking for a `.git` entry at
    each level, so a target nested inside an existing repo (e.g. a subdir of a
    monorepo) is correctly detected even though `target_dir` itself has no
    `.git`.
    """
    current = target_dir.resolve()
    while True:
        if (current / ".git").exists():
            return True
        parent = current.parent
        if parent == current:
            return False
        current = parent


def _git_init(target_dir: Path) -> None:
    """git-init `target_dir` if it is not already inside a repo.

    Strictly scoped to `target_dir` via `cwd=`; never touches the orchestrator
    repo's own `.git/`. A no-op when `target_dir` is already inside a repo
    (itself or an ancestor), so existing history is never re-initialized,
    nested, or lost.
    """
    if _inside_existing_repo(target_dir):
        return
    subprocess.run(["git", "init", "--quiet"], cwd=target_dir, check=True)


def _write_claude_md(target_dir: Path) -> None:
    """Write/merge `.claude/CLAUDE.md`'s binding-rules block. Add-if-absent."""
    claude_dir = target_dir / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    claude_md = claude_dir / "CLAUDE.md"
    if claude_md.exists():
        existing = claude_md.read_text(encoding="utf-8")
        if _RULES_SENTINEL in existing:
            return
        if not existing.endswith("\n"):
            existing += "\n"
        claude_md.write_text(existing + "\n" + _RULES_BLOCK, encoding="utf-8")
    else:
        claude_md.write_text(_RULES_BLOCK, encoding="utf-8")


def _write_settings_json(target_dir: Path) -> None:
    """Merge-safe write of `.claude/settings.json`.

    Preserves any existing keys; adds the marketplace + enabledPlugins entries
    and the deny-specs-edit PreToolUse hook only if absent.
    """
    claude_dir = target_dir / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    settings_path = claude_dir / "settings.json"

    if settings_path.exists():
        data: dict = json.loads(settings_path.read_text(encoding="utf-8"))
    else:
        data = {}

    marketplaces: dict = data.setdefault("extraKnownMarketplaces", {})
    marketplaces.setdefault(_MARKETPLACE_KEY, _MARKETPLACE_VALUE)

    plugins: dict = data.setdefault("enabledPlugins", {})
    plugins.setdefault(_PLUGIN_KEY, True)

    hooks: dict = data.setdefault("hooks", {})
    pre_tool_use: list = hooks.setdefault("PreToolUse", [])
    if _DENY_HOOK_ENTRY not in pre_tool_use:
        pre_tool_use.append(_DENY_HOOK_ENTRY)

    settings_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def _write_next_steps(target_dir: Path) -> None:
    """Write `project/NEXT_STEPS.md`. Idempotent: leaves an existing file untouched."""
    project_dir = target_dir / "project"
    project_dir.mkdir(parents=True, exist_ok=True)
    next_steps = project_dir / "NEXT_STEPS.md"
    if next_steps.exists():
        return
    project_name = target_dir.resolve().name
    next_steps.write_text(
        _NEXT_STEPS_TEMPLATE.format(project_name=project_name), encoding="utf-8"
    )


def _run_init(argv: list[str]) -> int:
    # `--target`/`--all`/`-h`/`--help` route to the pre-existing substrate
    # installer (specfuse.orchestrator.init); a bare directory is the new
    # T02 state-repo scaffold.
    if any(a in ("--target", "--all", "-h", "--help") for a in argv):
        from specfuse.orchestrator import init as init_mod

        old_argv = sys.argv
        sys.argv = ["specfuse-orchestrator init", *argv]
        try:
            return init_mod.main()
        finally:
            sys.argv = old_argv

    init_parser = argparse.ArgumentParser(
        prog="specfuse-orchestrator init", add_help=False
    )
    init_parser.add_argument("--git", action="store_true")
    init_parser.add_argument("target_dir", nargs="?")
    parsed, _unused = init_parser.parse_known_args(argv)

    if not parsed.target_dir:
        sys.stderr.write(
            "error: specfuse-orchestrator init requires a target directory "
            "(or --target <component|specs> <repo>)\n"
        )
        return 2

    target_dir = Path(parsed.target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    if parsed.git:
        _git_init(target_dir)
    _scaffold_state_dirs(target_dir)
    _write_claude_md(target_dir)
    _write_settings_json(target_dir)
    _write_next_steps(target_dir)
    return 0


def _substrate_mount_name() -> str:
    """The substrate mount dirname, derived from `_RULES_SENTINEL`.

    `_RULES_SENTINEL` (e.g. `@shared/rules/never-touch.md`) is the single
    source of truth for where the `.claude/CLAUDE.md` wiring expects the
    substrate to live; deriving the mount name from it (rather than a second
    hardcoded constant) makes the two surfaces structurally unable to drift.
    """
    return _RULES_SENTINEL.lstrip("@").split("/", 1)[0]


def _copy_substrate_tree(dst: Path) -> None:
    """Overlay-copy the packaged substrate tree into `dst`.

    Managed files are overwritten with the wheel's copy; any extra files
    already present under `dst` are left untouched (mirrors init.py's
    `copy_tree` overlay semantics).
    """
    src = paths.substrate()
    for root, dirs, files in os.walk(src):
        if "__pycache__" in dirs:
            dirs.remove("__pycache__")
        rel = Path(root).relative_to(src)
        target_root = dst if rel == Path(".") else dst / rel
        target_root.mkdir(parents=True, exist_ok=True)
        for name in files:
            shutil.copy2(Path(root) / name, target_root / name)


def provision_substrate(target_dir: Path) -> Path:
    """Sync the frozen substrate from the installed wheel into `target_dir`.

    Writes only under the substrate mount (`target_dir/<mount>`, mount name
    derived from `_RULES_SENTINEL`); never touches `STATE_DIRS` or
    `roadmap.md`. Returns the mount directory.
    """
    mount = target_dir / _substrate_mount_name()
    mount.mkdir(parents=True, exist_ok=True)
    _copy_substrate_tree(mount)
    return mount


def self_provision_if_stale(state_root: Path) -> bool:
    """Re-provision the substrate under `state_root` iff the wheel version has moved on.

    Compares the installed wheel's `__version__` against the stamp written by
    the previous provision (`<mount>/.substrate-version`). Only substrate
    files are touched; `STATE_DIRS` and `roadmap.md` are never written. Returns
    whether a (re-)provision happened, so callers/tests can assert steady-state
    runs are no-ops.
    """
    mount = state_root / _substrate_mount_name()
    stamp = mount / _SUBSTRATE_VERSION_STAMP
    if stamp.is_file() and stamp.read_text(encoding="utf-8").strip() == __version__:
        return False
    provision_substrate(state_root)
    stamp.write_text(__version__, encoding="utf-8")
    return True


def _run_upgrade(argv: list[str]) -> int:
    if not argv:
        sys.stderr.write(
            "error: specfuse-orchestrator upgrade requires a target directory\n"
        )
        return 2

    target_dir = Path(argv[0])
    target_dir.mkdir(parents=True, exist_ok=True)
    provision_substrate(target_dir)
    _write_claude_md(target_dir)
    _write_settings_json(target_dir)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="specfuse-orchestrator",
        description="Specfuse orchestrator: initiative-coordination drivers.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_subparser = subparsers.add_parser(
        "init",
        help="scaffold the orchestrator substrate into a target repo",
        add_help=False,
    )
    init_subparser.add_argument(
        "--git",
        action="store_true",
        help="also run `git init` (skipped when already inside a repo)",
    )
    subparsers.add_parser(
        "upgrade",
        help="sync the frozen substrate from the wheel into an existing install",
        add_help=False,
    )

    return parser


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    parser = build_parser()
    # parse_known_args, not parse_args: each subcommand's own flags (e.g.
    # init's --target/--dry-run, or a bare -h/--help meant for it) are none of
    # this dispatcher's business — they pass through to the subcommand handler.
    args, remainder = parser.parse_known_args(argv[:1])
    if args.command == "init":
        return _run_init([*argv[1:], *remainder])
    return _run_upgrade([*argv[1:], *remainder])


if __name__ == "__main__":
    sys.exit(main())
